### ISSUE TITLE
사파리에서 모바일 환경에서 댓글 창 넓이 overflow됨

### ISSUE THREAD

**Issue by kimjeongwonn** [kimjeongwonn/vlive-clone-coding#13]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/66168187/117114145-713ec100-adc6-11eb-9139-df5339293214.png">

@dooyeong20
위와 같이 넓이가 제대로 지정이 안되어 overflow됩니다.. 확인 부탁드려요

**Comment by dooyeong20** [comment]
수정완료하고 pr 보냈어요!!

#15
